# Generated by Django 3.0.3 on 2020-04-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dated', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendees',
            new_name='invitees',
        ),
    ]
